import { Knex } from 'knex';
import { ActionCategory, TABLES } from '../../shared/constants/tables';

export async function seed(knex: Knex): Promise<void> {
  await knex(TABLES.ENTITY_ACTION).del();

  await knex(TABLES.ENTITY_ACTION).insert([
    {
      action_key: 'contacts/list',
      entity_key: 'contacts',
      action_category: ActionCategory.READ,
      action_en_name: 'List Contacts',
      action_ar_name: 'عرض جهات الاتصال',
    },

    {
      action_key: 'dictionary/list',
      entity_key: 'dictionary',
      action_category: ActionCategory.READ,
      action_en_name: 'List Dictionary',
      action_ar_name: 'عرض القاموس',
    },

    {
      action_key: 'dashboard/list',
      entity_key: 'dashboard',
      action_category: ActionCategory.READ,
      action_en_name: 'List Dashboard',
      action_ar_name: 'عرض لوحة التحكم',
    },

    {
      action_key: 'settings/list',
      entity_key: 'settings',
      action_category: ActionCategory.READ,
      action_en_name: 'List Settings',
      action_ar_name: 'عرض الإعدادات',
    },

    {
      action_key: 'users/list',
      entity_key: 'users',
      action_category: ActionCategory.READ,
      action_en_name: 'List Users',
      action_ar_name: 'عرض المستخدمين',
    },
    {
      action_key: 'users/create',
      entity_key: 'users',
      action_category: ActionCategory.CREATE,
      action_en_name: 'Create Users',
      action_ar_name: 'إنشاء مستخدمين',
    },
    {
      action_key: 'users/update',
      entity_key: 'users',
      action_category: ActionCategory.UPDATE,
      action_en_name: 'Update Users',
      action_ar_name: 'تحديث المستخدمين',
    },
    {
      action_key: 'users/delete',
      entity_key: 'users',
      action_category: ActionCategory.DELETE,
      action_en_name: 'Delete Users',
      action_ar_name: 'حذف المستخدمين',
    },
    {
      action_key: 'users/permissions',
      entity_key: 'users',
      action_category: ActionCategory.UPDATE,
      action_en_name: 'Update User Permissions',
      action_ar_name: 'تحديث أذونات المستخدمين',
    },
    {
      action_key: 'users/assign-role',
      entity_key: 'users',
      action_category: ActionCategory.CREATE,
      action_en_name: 'Assign User Role',
      action_ar_name: 'تعيين دور للمستخدم',
    },

    {
      action_key: 'roles/list',
      entity_key: 'roles',
      action_category: ActionCategory.READ,
      action_en_name: 'List Roles',
      action_ar_name: 'عرض الأدوار',
    },
    {
      action_key: 'roles/create',
      entity_key: 'roles',
      action_category: ActionCategory.CREATE,
      action_en_name: 'Create Roles',
      action_ar_name: 'إنشاء أدوار',
    },
    {
      action_key: 'roles/update',
      entity_key: 'roles',
      action_category: ActionCategory.UPDATE,
      action_en_name: 'Update Roles',
      action_ar_name: 'تحديث الأدوار',
    },
    {
      action_key: 'roles/delete',
      entity_key: 'roles',
      action_category: ActionCategory.DELETE,
      action_en_name: 'Delete Roles',
      action_ar_name: 'حذف الأدوار',
    },
    {
      action_key: 'roles/permissions',
      entity_key: 'roles',
      action_category: ActionCategory.UPDATE,
      action_en_name: 'Update Role Permissions',
      action_ar_name: 'تحديث أذونات الأدوار',
    },

    {
      action_key: 'groups/list',
      entity_key: 'groups',
      action_category: ActionCategory.READ,
      action_en_name: 'List Groups',
      action_ar_name: 'عرض المجموعات',
    },
    {
      action_key: 'groups/create',
      entity_key: 'groups',
      action_category: ActionCategory.CREATE,
      action_en_name: 'Create Groups',
      action_ar_name: 'إنشاء مجموعات',
    },
    {
      action_key: 'groups/update',
      entity_key: 'groups',
      action_category: ActionCategory.UPDATE,
      action_en_name: 'Update Groups',
      action_ar_name: 'تحديث المجموعات',
    },
    {
      action_key: 'groups/delete',
      entity_key: 'groups',
      action_category: ActionCategory.DELETE,
      action_en_name: 'Delete Groups',
      action_ar_name: 'حذف المجموعات',
    },
    {
      action_key: 'groups/assign-role',
      entity_key: 'groups',
      action_category: ActionCategory.CREATE,
      action_en_name: 'Assign Group Role',
      action_ar_name: 'تعيين دور للمجموعة',
    },
    {
      action_key: 'groups/add-users',
      entity_key: 'groups',
      action_category: ActionCategory.CREATE,
      action_en_name: 'Add User To Group',
      action_ar_name: 'اضافة مستخدمين للمجموعة',
    },

    {
      action_key: 'plans/list',
      entity_key: 'plans',
      action_category: ActionCategory.READ,
      action_en_name: 'List Plans',
      action_ar_name: 'عرض الخطط',
    },
    {
      action_key: 'plans/create',
      entity_key: 'plans',
      action_category: ActionCategory.CREATE,
      action_en_name: 'Create Plans',
      action_ar_name: 'إنشاء خطط',
    },
    {
      action_key: 'plans/update',
      entity_key: 'plans',
      action_category: ActionCategory.UPDATE,
      action_en_name: 'Update Plans',
      action_ar_name: 'تحديث الخطط',
    },
    {
      action_key: 'plans/delete',
      entity_key: 'plans',
      action_category: ActionCategory.DELETE,
      action_en_name: 'Delete Plans',
      action_ar_name: 'حذف الخطط',
    },
    {
      action_key: 'invoices/list',
      entity_key: 'invoices',
      action_category: ActionCategory.READ,
      action_en_name: 'List Invoices',
      action_ar_name: 'عرض الفواتير',
    },
    {
      action_key: 'invoices/create',
      entity_key: 'invoices',
      action_category: ActionCategory.CREATE,
      action_en_name: 'Create Invoices',
      action_ar_name: 'إنشاء فواتير',
    },
    {
      action_key: 'invoices/update',
      entity_key: 'invoices',
      action_category: ActionCategory.UPDATE,
      action_en_name: 'Update Invoices',
      action_ar_name: 'تحديث الفواتير',
    },
    {
      action_key: 'invoices/delete',
      entity_key: 'invoices',
      action_category: ActionCategory.DELETE,
      action_en_name: 'Delete Invoices',
      action_ar_name: 'حذف الفواتير',
    },
    {
      action_key: 'payments/list',
      entity_key: 'payments',
      action_category: ActionCategory.READ,
      action_en_name: 'List Payments',
      action_ar_name: 'عرض المدفوعات',
    },
    {
      action_key: 'payments/create',
      entity_key: 'payments',
      action_category: ActionCategory.CREATE,
      action_en_name: 'Create Payments',
      action_ar_name: 'إنشاء مدفوعات',
    },
    {
      action_key: 'payments/update',
      entity_key: 'payments',
      action_category: ActionCategory.UPDATE,
      action_en_name: 'Update Payments',
      action_ar_name: 'تحديث المدفوعات',
    },
    {
      action_key: 'payments/delete',
      entity_key: 'payments',
      action_category: ActionCategory.DELETE,
      action_en_name: 'Delete Payments',
      action_ar_name: 'حذف المدفوعات',
    },
    {
      action_key: 'dues/list',
      entity_key: 'dues',
      action_category: ActionCategory.READ,
      action_en_name: 'List Dues',
      action_ar_name: 'عرض المستحقات',
    },
    {
      action_key: 'dues/create',
      entity_key: 'dues',
      action_category: ActionCategory.CREATE,
      action_en_name: 'Create Dues',
      action_ar_name: 'إنشاء مستحقات',
    },
    {
      action_key: 'dues/update',
      entity_key: 'dues',
      action_category: ActionCategory.UPDATE,
      action_en_name: 'Update Dues',
      action_ar_name: 'تحديث المستحقات',
    },
    {
      action_key: 'dues/delete',
      entity_key: 'dues',
      action_category: ActionCategory.DELETE,
      action_en_name: 'Delete Dues',
      action_ar_name: 'حذف المستحقات',
    },
    {
      action_key: 'configurations/list',
      entity_key: 'configurations',
      action_category: ActionCategory.READ,
      action_en_name: 'List Configurations',
      action_ar_name: 'عرض الضبط',
    },
    {
      action_key: 'configurations/create',
      entity_key: 'configurations',
      action_category: ActionCategory.CREATE,
      action_en_name: 'Create Configurations',
      action_ar_name: 'إنشاء ضبط',
    },
    {
      action_key: 'configurations/update',
      entity_key: 'configurations',
      action_category: ActionCategory.UPDATE,
      action_en_name: 'Update Configurations',
      action_ar_name: 'تحديث الضبط',
    },
    {
      action_key: 'configurations/delete',
      entity_key: 'configurations',
      action_category: ActionCategory.DELETE,
      action_en_name: 'Delete Configurations',
      action_ar_name: 'حذف الضبط',
    },
    {
      action_key: 'customers/list',
      entity_key: 'customers',
      action_category: ActionCategory.READ,
      action_en_name: 'List Customers',
      action_ar_name: 'عرض العملاء',
    },
    {
      action_key: 'customers/create',
      entity_key: 'customers',
      action_category: ActionCategory.CREATE,
      action_en_name: 'Create Customers',
      action_ar_name: 'إنشاء عملاء',
    },
    {
      action_key: 'customers/update',
      entity_key: 'customers',
      action_category: ActionCategory.UPDATE,
      action_en_name: 'Update Customers',
      action_ar_name: 'تحديث العملاء',
    },
    {
      action_key: 'customers/delete',
      entity_key: 'customers',
      action_category: ActionCategory.DELETE,
      action_en_name: 'Delete Customers',
      action_ar_name: 'حذف العملاء',
    },
    {
      action_key: 'subscriptions/list',
      entity_key: 'subscriptions',
      action_category: ActionCategory.READ,
      action_en_name: 'List Subscriptions',
      action_ar_name: 'عرض الاشتراكات',
    },
    {
      action_key: 'subscriptions/create',
      entity_key: 'subscriptions',
      action_category: ActionCategory.CREATE,
      action_en_name: 'Create Subscriptions',
      action_ar_name: 'إنشاء اشتراكات',
    },
    {
      action_key: 'subscriptions/update',
      entity_key: 'subscriptions',
      action_category: ActionCategory.UPDATE,
      action_en_name: 'Update Subscriptions',
      action_ar_name: 'تحديث الاشتراكات',
    },
    {
      action_key: 'subscriptions/delete',
      entity_key: 'subscriptions',
      action_category: ActionCategory.DELETE,
      action_en_name: 'Delete Subscriptions',
      action_ar_name: 'حذف الاشتراكات',
    },
  ]);
}
