import { Knex } from 'knex';
import { TABLES } from '../../shared/constants/tables';

export async function seed(knex: Knex): Promise<void> {
  await knex(TABLES.USER_ENTITY_ACTION).del();

  await knex(TABLES.USER_ENTITY_ACTION).insert([
    { email: 'super-admin@gmail.com', action_key: 'dashboard/list' },
    { email: 'super-admin@gmail.com', action_key: 'settings/list' },
    { email: 'super-admin@gmail.com', action_key: 'users/list' },
    { email: 'super-admin@gmail.com', action_key: 'users/create' },
    { email: 'super-admin@gmail.com', action_key: 'users/update' },
    { email: 'super-admin@gmail.com', action_key: 'users/delete' },
    { email: 'super-admin@gmail.com', action_key: 'users/permissions' },
    { email: 'super-admin@gmail.com', action_key: 'users/assign-role' },
    { email: 'super-admin@gmail.com', action_key: 'roles/list' },
    { email: 'super-admin@gmail.com', action_key: 'roles/create' },
    { email: 'super-admin@gmail.com', action_key: 'roles/update' },
    { email: 'super-admin@gmail.com', action_key: 'roles/delete' },
    { email: 'super-admin@gmail.com', action_key: 'roles/permissions' },
    { email: 'super-admin@gmail.com', action_key: 'groups/list' },
    { email: 'super-admin@gmail.com', action_key: 'groups/create' },
    { email: 'super-admin@gmail.com', action_key: 'groups/update' },
    { email: 'super-admin@gmail.com', action_key: 'groups/delete' },
    { email: 'super-admin@gmail.com', action_key: 'groups/assign-role' },
    { email: 'super-admin@gmail.com', action_key: 'groups/add-users' },
    { email: 'super-admin@gmail.com', action_key: 'plans/list' },
    { email: 'super-admin@gmail.com', action_key: 'plans/create' },
    { email: 'super-admin@gmail.com', action_key: 'plans/update' },
    { email: 'super-admin@gmail.com', action_key: 'plans/delete' },
    { email: 'super-admin@gmail.com', action_key: 'invoices/list' },
    { email: 'super-admin@gmail.com', action_key: 'invoices/create' },
    { email: 'super-admin@gmail.com', action_key: 'invoices/update' },
    { email: 'super-admin@gmail.com', action_key: 'invoices/delete' },
    { email: 'super-admin@gmail.com', action_key: 'payments/list' },
    { email: 'super-admin@gmail.com', action_key: 'payments/create' },
    { email: 'super-admin@gmail.com', action_key: 'payments/update' },
    { email: 'super-admin@gmail.com', action_key: 'payments/delete' },
    { email: 'super-admin@gmail.com', action_key: 'dues/list' },
    { email: 'super-admin@gmail.com', action_key: 'dues/create' },
    { email: 'super-admin@gmail.com', action_key: 'dues/update' },
    { email: 'super-admin@gmail.com', action_key: 'dues/delete' },
    { email: 'super-admin@gmail.com', action_key: 'customers/list' },
    { email: 'super-admin@gmail.com', action_key: 'customers/create' },
    { email: 'super-admin@gmail.com', action_key: 'customers/update' },
    { email: 'super-admin@gmail.com', action_key: 'customers/delete' },
    { email: 'super-admin@gmail.com', action_key: 'subscriptions/list' },
    { email: 'super-admin@gmail.com', action_key: 'subscriptions/create' },
    { email: 'super-admin@gmail.com', action_key: 'subscriptions/update' },
    { email: 'super-admin@gmail.com', action_key: 'subscriptions/delete' },
    { email: 'super-admin@gmail.com', action_key: 'configurations/list' },
    { email: 'super-admin@gmail.com', action_key: 'configurations/create' },
    { email: 'super-admin@gmail.com', action_key: 'configurations/update' },
    { email: 'super-admin@gmail.com', action_key: 'configurations/delete' },

    { email: 'admin@gmail.com', action_key: 'users/list' },
    { email: 'admin@gmail.com', action_key: 'users/create' },
    { email: 'admin@gmail.com', action_key: 'users/update' },
    { email: 'admin@gmail.com', action_key: 'users/delete' },
    { email: 'admin@gmail.com', action_key: 'roles/list' },
    { email: 'admin@gmail.com', action_key: 'roles/create' },
    { email: 'admin@gmail.com', action_key: 'roles/update' },
    { email: 'admin@gmail.com', action_key: 'roles/delete' },
    { email: 'admin@gmail.com', action_key: 'subscriptions/list' },
    { email: 'admin@gmail.com', action_key: 'subscriptions/create' },
    { email: 'admin@gmail.com', action_key: 'subscriptions/update' },
    { email: 'admin@gmail.com', action_key: 'subscriptions/delete' },

    { email: 'manager@gmail.com', action_key: 'dashboard/list' },

    { email: 'developer@gmail.com', action_key: 'contacts/list' },
    { email: 'developer@gmail.com', action_key: 'dictionary/list' },
  ]);
}
