const CACHED_KEYS = {
  LOGGED_USER: "LOGGED_USER",
  LOGGED_USER_PERMISSIONS: "LOGGED_USER_PERMISSIONS",
  LOGGED_USER_ACTIONS: "LOGGED_USER_ACTIONS",
  USER_DETAILS: "USER_DETAILS",
  ROLE_DETAILS: "ROLE_DETAILS",
  GROUP_DETAILS: "GROUP_DETAILS",
  SYSTEM_PERMISSIONS: "SYSTEM_PERMISSIONS",
  USER_ACTIONS: "USER_ACTIONS",
  ROLE_ACTIONS: "ROLE_ACTIONS",
};
export default CACHED_KEYS;
